### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Mikey1-nuel** [Mikey1-nuel/Ruby_Catalog_Group_Capstone#24]
[Kanban board](https://github.com/Mikey1-nuel/Ruby_Catalog_Group_Capstone/projects/1)

We are a team of 3 members

Team member 1: @Mikey1-nuel
Team member 2: @tomdan-ai
Team member 3: @Bellagirl-maker

**Comment by abdulhamiid** [comment]
# Status: Required Changes :recycle:
Hi Team 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

According to the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md)
- Please ensure that every card on your board has:
  - The number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work.
  - A description of the task. ☺
  
![image](https://github.com/Mikey1-nuel/Ruby_Catalog_Group_Capstone/assets/78251927/5d458d8a-edbc-4b32-a4fb-1e84fb47a890)

![image](https://github.com/Mikey1-nuel/Ruby_Catalog_Group_Capstone/assets/78251927/88336fcb-ff35-4ce2-b0c1-db2c5428d041)


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by TuyishimireEric** [comment]
# Status: APPROVED 🟢  
### Hi  @TEAM 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Made suggested changes 👍 
✔ Descriptive Kanban board 👍

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
